### ISSUE TITLE
Vertaisarviointi_2

### ISSUE THREAD

**Issue by JanneKarki** [rheikkinen/tiralabra-connect4#2]
Sovellus ladattu 25.8. klo 18:38 git clone komennolla.

Määrittelydokumenttiin tutustuminen alusti hyvin sen mistä sovelluksessa on kysymys. Sen pohjalta saa käsityksen että työn suunnitteluun on paneuduttu huolellisesti. Itse toteutusdokumentti kuvaa napakasti sen rakenteen ja tekoälyn toteutuksen algoritmeineen. Tesatusdokumentissa taas on kuvattu selkeästi ja monipuolisesti yksikkötestauksen sisältö. Empiirinen testaus on vielä vaiheessa.

Ohjelmointiyyli on erittäin hyvä. Koodia on mukava lukea ja sitä helppo ymmärtää, kun muuttujat ja metodit on kuvaavasti nimetty. Metodit hoitavat omia selkeitä vastuitaan ja docstring-kommentointia on käytetty ahkerasti kuvaamaan niiden toimintaa. Luokille ei ollut kuitenkaan vielä lisätty kommentteja, jotka ehkä voisi vielä lisätä kuvaamaan niiden toimintaa.

GameBoard vastaa pelin logiikasta, ConnectFour tarjoaa pelin käyttöliittymän ja AI luonnollisesti tarjoaa tekoälyn. Moduuli constants pitää vakiomuuttujat selkeästi erillään muusta koodista, josta ne on kaikki tarvittaessa helposti löydettävissä samasta paikasta. Voisvatko AI-luokan MAX_ ja MIN_SCORE:t olla myös siellä? 

Sovellus on tiivis ja hyvin totetutettu kokonaisuus, josta en virheitä löytänyt ja parannettavaa on hyvin vaikea keksiä. Toki graafinen käyttöliittymä toisi mukavuutta, mutta se ei kuitenkaan kuulu kurssin tavoitteisiin.

Tekoäly oli tehokas ja haastava vastus. Pisteytys on oikein hyvä lisä, josta näkee omat voiton mahdollisuudet ja oppii samalla myös omista virheistään. Sen avulla tekoäly onnistui lopulta voittaa.

Hienoa työtä!

**Comment by rheikkinen** [comment]
Hyviä ja osuvia havaintoja, kiitos kommentista! Vaikka se onkin tällä kurssilla toissijaisempi juttu, niin olen samaa mieltä, että graafinen käyttöliittymä olisi mukava lisä, ja se onkin ollut about joka viikko to do -listalla "jos jää aikaa, niin lisään" -tyyppisesti. Haluan ainakin jotain siistimistä tehdä, nykyinen taulukko ykkösillä ja kakkosilla ei mielestäni tarjoa ihan sitä helpointa ja mukavinta pelikokemusta.
